### ISSUE TITLE
Failed to activate the fold-lines package

### ISSUE THREAD

**Issue by RTSchriner** [alysov/fold-lines#1]
On starting Atom.

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [fold-lines](https://github.com/alysov/fold-lines) package, v0.1.0
### Stack Trace

Failed to activate the fold-lines package

```
At editor.displayBuffer.getFoldMarkerAttributes is not a function

TypeError: editor.displayBuffer.getFoldMarkerAttributes is not a function
    at /Users/rileyschriner/.atom/packages/fold-lines/lib/fold-lines.coffee:13:57
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:282:9)
    at Object.module.exports.FoldLines.activate (/Users/rileyschriner/.atom/packages/fold-lines/lib/fold-lines.coffee:9:39)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:686:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:85:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "markdown-preview",
      "wrap-guide",
      "atom-wordpress"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.14
autoclose-html, v0.19.0
emmet, v2.3.17
fold-lines, v0.1.0
git-log, v0.4.1
markdown-preview-plus, v2.2.2
minimap, v4.18.0
my-github-profile, v0.2.1
pigments, v0.19.3
seti-ui, v0.8.1
statusbar-datetime, v0.9.7
wordpress-dictionary, v4.4.0

# Dev
No dev packages
```

**Comment by alysov** [comment]
Thank you for reporting this.  I'll look into it as soon as I can.

**Comment by JasCodes** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Enterprise N
**Thrown From**: [fold-lines](https://github.com/alysov/fold-lines) package, v0.1.0

### Stack Trace

Failed to activate the fold-lines package

```
At editor.displayBuffer.getFoldMarkerAttributes is not a function

TypeError: editor.displayBuffer.getFoldMarkerAttributes is not a function
    at file:///C:/Users/jas/.atom/packages/fold-lines/lib/fold-lines.coffee:13:57
    at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\workspace.js:282:9)
    at Object.module.exports.FoldLines.activate (file:///C:/Users/jas/.atom/packages/fold-lines/lib/fold-lines.coffee:9:39)
    at Package.module.exports.Package.activateNow (C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:170:19)
    at C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:517:21)
    at C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\atom-environment.js:686:21)
    at module.exports (C:\Users\jas\AppData\Local\atom\app-1.3.2\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/jas/AppData/Local/atom/app-1.3.2/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/jas/AppData/Local/atom/app-1.3.2/resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "line-ending-selector",
      "atom-terminal-panel",
      "project-manager",
      "atom-runner",
      "git-control",
      "tool-bar-almighty",
      "seti-icons",
      "file-icon-supplement",
      "tool-bar-main",
      "nuclide-debugger-hhvm",
      "node-debugger",
      "autocomplete-project-paths",
      "activate-power-mode",
      "git-projects",
      "git-clone",
      "nuclide-buck-files",
      "nuclide-busy-signal",
      "nuclide-clipboard-path",
      "nuclide-code-format",
      "nuclide-code-highlight"
    ],
    "packagesWithKeymapsDisabled": [
      "activate-power-mode"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.10
atom-material-ui, v0.8.0
autocomplete-cmake, v0.3.1
autocomplete-glsl, v0.2.3
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
custom-title, v1.0.1
dockerletion, v0.1.0
file-icons, v1.6.13
flex-tool-bar, v0.7.2
fold-lines, v0.1.0
hyperclick, v0.0.35
icon-fonts, v1.10.0
language-batch, v0.3.3
language-cmake, v0.1.4
language-cpp14, v0.5.0
language-cuda, v0.1.0
language-docker, v1.1.6
line-ending-selector-unix, v0.0.9
linter, v1.11.3
linter-gcc, v0.5.8
linter-node-markdownlint, v0.2.2
markdown-preview-opener, v0.1.1
minimap, v4.18.2
project-viewer, v0.2.25
run-in-terminal, v0.5.0
sync-settings, v0.6.0
tool-bar, v0.1.9
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by ryanjbonnell** [comment]
I get the same error message when trying to install [fold-lines](https://github.com/alysov/fold-lines) 0.10.0 with Atom 1.3.3 on Mac OS X 10.11.2 "El Capitan".

**Comment by n-a-m-e** [comment]
Im getting it aswell when trying to install
os:arch linux
atom:1.3.3
foldlines:0.1.0
error:editor.displayBuffer.getFoldMarkerAttributes is not a function

<pre><code>
TypeError: editor.displayBuffer.getFoldMarkerAttributes is not a function
    at /home/username/.atom/packages/fold-lines/lib/fold-lines.coffee:13:57
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:282:9)
    at Object.module.exports.FoldLines.activate (/home/username/.atom/packages/fold-lines/lib/fold-lines.coffee:9:39)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:170:19)
    at /usr/share/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:517:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:333:19
    at /usr/share/atom/resources/app.asar/src/config.js:624:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:809:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:601:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app.asar/src/config.js:379:12)
    at Package.module.exports.Package.enable (/usr/share/atom/resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:162:14)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
</code></pre>

**Comment by WeAreGeek** [comment]
I too get this error when installing and enabling fold-lines 0.1.0:

**Atom Version**: 1.4.0
**System**: Ubuntu 14.04.3
**Thrown From**: [fold-lines](https://github.com/alysov/fold-lines) package, v0.1.0

### Stack Trace

Failed to activate the fold-lines package

```
At editor.displayBuffer.getFoldMarkerAttributes is not a function

TypeError: editor.displayBuffer.getFoldMarkerAttributes is not a function
    at /home/***/.atom/packages/fold-lines/lib/fold-lines.coffee:13:57
    at Workspace.module.exports.Workspace.observeTextEditors (/opt/atom/resources/app.asar/src/workspace.js:288:9)
    at Object.module.exports.FoldLines.activate (/home/***/.atom/packages/fold-lines/lib/fold-lines.coffee:9:39)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:183:20)
    at /opt/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at /opt/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:524:21)
    at /opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /opt/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
fold-lines, v0.1.0

# Dev
No dev packages
```

**Comment by markandrewj** [comment]
Hello, I am getting this error with atom 1.9.0-beta0 and foldlines@0.2.0, under ubuntu 16.04.

```
TypeError: Cannot read property 'getMarkers' of undefined
    at /home/tinymouse/.atom/packages/fold-lines/lib/fold-lines.coffee:13:27
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom-beta/resources/app.asar/src/workspace.js:309:9)
    at Object.module.exports.FoldLines.activate (/home/tinymouse/.atom/packages/fold-lines/lib/fold-lines.coffee:9:39)
    at Package.module.exports.Package.activateNow (/usr/share/atom-beta/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom-beta/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom-beta/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom-beta/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom-beta/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom-beta/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom-beta/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom-beta/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom-beta/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom-beta/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom-beta/resources/app.asar/src/atom-environment.js:760:28

```
