### ISSUE TITLE
After update to version 1.9.0, Failed to activate the fold-lines package

### ISSUE THREAD

**Issue by evandrocoan** [alysov/fold-lines#4]
After update to version 1.9.0:

**Atom Version**: 1.9.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [fold-lines](https://github.com/alysov/fold-lines) package, v0.2.0
### Stack Trace

Failed to activate the fold-lines package

```
At Cannot read property 'getMarkers' of undefined

TypeError: Cannot read property 'getMarkers' of undefined
    at file:///C:/Users/Professional/.atom/packages/fold-lines/lib/fold-lines.coffee:13:27
    at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\workspace.js:309:9)
    at Object.module.exports.FoldLines.activate (file:///C:/Users/Professional/.atom/packages/fold-lines/lib/fold-lines.coffee:9:39)
    at Package.module.exports.Package.activateNow (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\atom-environment.js:760:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.cpp": [
        "sma",
        "inc"
      ]
    },
    "disabledPackages": [
      "minimap",
      "trailing-spaces",
      "save-commands",
      "wrap-guide"
    ],
    "themes": [
      "aesthetic-ui",
      "notepad-plus-plus-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aesthetic-ui, v2.0.0 (inactive)
atom-beautify, v0.29.10 (inactive)
atom-no-tab-close-button, v1.0.0 (inactive)
atom-shell-commands, v1.4.0 (inactive)
atom-user-commands, v0.1.4 (inactive)
bade3-notepad-syntax, v0.3.4 (inactive)
cfeclipse-light-syntax, v0.1.6 (inactive)
climate-syntax, v5.0.0 (inactive)
climate-ui, v4.5.0 (inactive)
eclectic-syntax, v0.2.1 (inactive)
file-types, v0.5.4-p1 (inactive)
fold-lines, v0.2.0 (inactive)
github-atom-light-syntax, v0.2.0 (inactive)
hipster-syntax, v0.0.3 (inactive)
indent-guide-improved, v1.4.9 (inactive)
indentation-indicator, v1.0.0 (inactive)
language-assembly, v0.6.2 (inactive)
language-batchfile, v0.4.0 (inactive)
minimap, v4.24.7 (inactive)
minimap-cursorline, v0.2.0 (inactive)
minimap-find-and-replace, v4.5.1 (inactive)
minimap-highlight-selected, v4.4.0 (inactive)
minimap-pigments, v0.2.1 (inactive)
minimap-selection, v4.4.0 (inactive)
minimap-split-diff, v0.3.1 (inactive)
multi-highlight-selected, v2.0.0 (inactive)
multi-wrap-guide, v0.25.1 (inactive)
northem-atom-syntax, v0.20.0 (inactive)
northem-atom-ui, v0.5.0 (inactive)
northem-dark-atom-syntax, v0.20.0 (inactive)
northem-dark-atom-ui, v0.5.0 (inactive)
northem-light-atom-syntax, v0.19.1 (inactive)
northem-light-atom-ui, v0.4.0 (inactive)
notepad-plus-plus-syntax, v0.1.3 (inactive)
open-recent, v5.0.0 (inactive)
paraiso-dark, v1.3.1 (inactive)
paraiso-light, v1.3.1 (inactive)
phpeclipse-syntax, v1.1.0 (inactive)
run-command2, v1.12.2 (inactive)
run-in-terminal, v0.6.0 (inactive)
save-autorun, v0.3.3 (inactive)
script-runner, v1.8.4 (inactive)
tabs-to-spaces, v1.0.2 (inactive)
text-manipulation, v0.6.0 (inactive)
theme-realgithub, v1.0.4 (inactive)
todo-show, v1.7.0 (inactive)
trailing-spaces, v0.3.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.38.1 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.0 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by CommiNazi** [comment]
C:\Users{user}.atom\packages\fold-lines\lib\fold-lines.coffee
Line 10: 
    From:   editor.displayBuffer.foldsMarkerLayer
    To:     editor.displayLayer.foldsMarkerLayer

**Comment by evandrocoan** [comment]
Thanks @CommiNazi

**Comment by shanept** [comment]
I found I have this same issue in atom. I have found this issue and confirmed that the version I have contains this commit, and it does.
However, it still doesn't work. It seems I do not have "editor.displayLayer". Reverting to "editor.displayBuffer" got the plugin working for me...

Any idea what's going on here?
